version: '3'
services:
  jekyll:
    image: jekyll
    container_name: jekyll
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --livereload --host 0.0.0.0
    ports:
      - 4000:4000
    volumes:
      - ./:/srv/jekyll/
